package constants;

public @interface TableColumn {
    String ASSESSMENT = "ASSESSMENT";
    String GRADE = "GRADE";
    String STUDENT_ID_DATA = "STUDENT_ID_DATA";
    String STUDENT_ID = "STUDENT_ID";
    String START_DATE_DATA = "START_DATE_DATA";
    String START_DATE = "START_DATE";
    String END_DATE_DATA = "END_DATE_DATA";
    String END_DATE = "END_DATE";
    String LOGIN_ID = "LOGIN_ID";
    String ACCOUNT_NUMBER_DATA = "ACCOUNT_NUMBER_DATA";
    String ACCOUNT_NUMBER = "ACCOUNT_NUMBER";
    String SUBJECT = "SUBJECT";
    String LONG_DESCRIPTION = "LONG_DESCRIPTION";
    String DESCRIPTION = "DESCRIPTION";
    String ROW_COUNT_DATA = "ROW_COUNT_DATA";
    String EVENT_ID = "EVENT_ID";
    String USER_NAME = "USER_NAME";
    String SHORT_DESCRIPTION = "SHORT_DESCRIPTION";
}
